[package]
name = "object_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
zip = "2.1.6"
image = "0.25.2"
serde = { version = "1", features = ["derive"] }
ron = "0.8.1" # I want this to be called ron serde, for no reason in particular.